---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found"
          name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: db
                  key: MYSQL_HOST
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: MYSQL_PASSWORD
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: db
                  key: MYSQL_PORT
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: MYSQL_USER
          ports:
            - containerPort: 3306

          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
