---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server
  namespace: default
  labels:
    app: python-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: python-api
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m

---
kind: Service
apiVersion: v1
metadata:
  name: python-service
  namespace: default
spec:
  selector:
    app: python-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: python-ingress
  namespace: default
  annotations:
    allow.http: "false"
spec:
  rules:
    - host: app.rancher.mathdevops.tk
      http:
        paths:
          - path: /
            backend:
              serviceName: python-service
              servicePort: 80
